### ISSUE TITLE
I suggest you upgrade the `enum-flags` to the latest version

### ISSUE THREAD

**Issue by mokeyish** [NLnetLabs/krill-kmip-protocol#11]
https://github.com/NLnetLabs/krill-kmip-protocol/blob/05a6e201a72870cf94d7d29b872ddcdb232c26b2/Cargo.toml#L11

<img width="1265" alt="图片" src="https://user-images.githubusercontent.com/16131917/128800836-b7b9a235-1790-4f7c-91ad-00ef4ff103e2.png">

**Comment by ximon18** [comment]
Thanks @mokeyish!
